### ISSUE TITLE
regexp too inclusive

### ISSUE THREAD

**Issue by snoyes** [nasa/ROSES-Compliance-Checking-Tools#2]
https://github.com/nasa/ROSES-Compliance-Checking-Tools/blob/0c2895b0d4cea6d6dda9f6e61ee3f272188edc33/check_dapr_single.py#L53

Should check for word boundaries to reduce false positive rate for text like "yet always" or "planet albedo"

**Comment by snoyes** [comment]
Should also handle mixed case.

**Comment by mansdell** [comment]
Added word boundary checks to re.finditer() to reduce false positive rate for "et al"
