### ISSUE TITLE
Incomplete pronoun check

### ISSUE THREAD

**Issue by snoyes** [nasa/ROSES-Compliance-Checking-Tools#3]
https://github.com/nasa/ROSES-Compliance-Checking-Tools/blob/0c2895b0d4cea6d6dda9f6e61ee3f272188edc33/check_dapr_single.py#L219

Missing "him".

https://github.com/nasa/ROSES-Compliance-Checking-Tools/blob/0c2895b0d4cea6d6dda9f6e61ee3f272188edc33/check_dapr_single.py#L235

Because the pronouns are surrounded by spaces, the code will not catch them where the word is bordered by punctuation, or starts or ends a line. It will also alert some false positives when a name or city happens to appear inside another word. Using a regexp to search for those words surrounded by word boundaries would solve both problems.

**Comment by mansdell** [comment]
Added 'him' and removed spaces around pronouns and updated code to consider word boundaries. Also fixed bug that wasn't reporting multiple occurrences of a word on the same page.

**Comment by snoyes** [comment]
And "hers" ?

**Comment by mansdell** [comment]
Added 'hers' as this was previously have been caught by 'her' before word boundaries.
